[package]
name = "project_smartypants"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.1"
serde = "1.0.214"
serde_json = "1.0.132"
